# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven Rozan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: testing
      run: mvn test

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
    - name: Setup Go environment
      uses: actions/setup-go@v5.0.1
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks.
        go-version: # optional
        # Path to the go.mod or go.work file.
        go-version-file: # optional
        # Set this option to true if you want the action to always check for the latest available version that satisfies the version spec
        check-latest: # optional
        # Used to pull Go distributions from go-versions. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
        token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
        # Used to specify whether caching is needed. Set to true, if you'd like to enable caching.
        cache: # optional, default is true
        # Used to specify the path to a dependency file - go.sum
        cache-dependency-path: # optional
        # Target architecture for Go to use. Examples: x86, x64. Will use system architecture by default.
        architecture: # optional
            
